// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: user/user.service.proto

package user

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/wrappers"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "github.com/liov/tiga/protobuf/utils/empty"
	_ "github.com/liov/tiga/protobuf/utils/oauth"
	_ "github.com/liov/tiga/protobuf/utils/proto/gogo"
	_ "github.com/liov/tiga/protobuf/utils/proto/patch"
	_ "github.com/liov/tiga/protobuf/utils/request"
	_ "github.com/liov/tiga/protobuf/utils/response"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *SingUpVerifyReq) Validate() error {
	return nil
}
func (this *SignupReq) Validate() error {
	if !(len(this.Password) > 5) {
		return github_com_mwitkow_go_proto_validators.FieldError("Password", fmt.Errorf(`密码最短6位`))
	}
	return nil
}
func (this *ActiveReq) Validate() error {
	return nil
}
func (this *EditReq) Validate() error {
	if this.Details != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Details); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Details", err)
		}
	}
	return nil
}
func (this *EditReq_EditDetails) Validate() error {
	for _, item := range this.EduExps {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("EduExps", err)
			}
		}
	}
	for _, item := range this.WorkExps {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("WorkExps", err)
			}
		}
	}
	return nil
}
func (this *LoginReq) Validate() error {
	if !(len(this.Password) > 6) {
		return github_com_mwitkow_go_proto_validators.FieldError("Password", fmt.Errorf(`密码错误`))
	}
	return nil
}
func (this *LoginRep) Validate() error {
	if this.User != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.User); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("User", err)
		}
	}
	return nil
}
func (this *ResetPasswordReq) Validate() error {
	return nil
}
func (this *ActionLogListReq) Validate() error {
	return nil
}
func (this *ActionLogListRep) Validate() error {
	for _, item := range this.List {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("List", err)
			}
		}
	}
	return nil
}
func (this *SendVerifyCodeReq) Validate() error {
	return nil
}
func (this *BaseListReq) Validate() error {
	return nil
}
func (this *BaseListRep) Validate() error {
	for _, item := range this.List {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("List", err)
			}
		}
	}
	return nil
}
func (this *UserRep) Validate() error {
	if this.User != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.User); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("User", err)
		}
	}
	if this.UerExt != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.UerExt); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("UerExt", err)
		}
	}
	return nil
}
func (this *FollowReq) Validate() error {
	return nil
}
