Module = "test"
# dev | test | prod
# 命令行参数获取
# Env = "dev"
# 不需要注入的dao
NoInject = ["Cache","Apollo","Etcd"]

[configCenter]
Watch  = false
[configCenter.nacos]
Addr = "nacos.default"
Group = "hoper"


[dev]
# 本地开发配置文件
LocalConfigName = "local.toml"

[test]
NacosTenant = "b5b476ab-774f-4637-a8bf-e915635b4b24"

[prod]
NacosTenant = ""