// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: content/moment.service.proto

package content

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "github.com/liov/tiga/protobuf/common"
	_ "github.com/liov/tiga/protobuf/user"
	_ "github.com/liov/tiga/protobuf/utils/area"
	_ "github.com/liov/tiga/protobuf/utils/empty"
	_ "github.com/liov/tiga/protobuf/utils/oauth"
	_ "github.com/liov/tiga/protobuf/utils/proto/gogo"
	_ "github.com/liov/tiga/protobuf/utils/proto/patch"
	_ "github.com/liov/tiga/protobuf/utils/request"
	_ "github.com/liov/tiga/protobuf/utils/response"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *AddMomentReq) Validate() error {
	return nil
}
func (this *MomentListReq) Validate() error {
	return nil
}
func (this *MomentListRep) Validate() error {
	for _, item := range this.List {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("List", err)
			}
		}
	}
	for _, item := range this.Users {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Users", err)
			}
		}
	}
	return nil
}
func (this *MomentRep) Validate() error {
	if this.Book != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Book); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Book", err)
		}
	}
	if this.Mood != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Mood); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Mood", err)
		}
	}
	if this.Weather != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Weather); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Weather", err)
		}
	}
	if this.Area != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Area); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Area", err)
		}
	}
	for _, item := range this.Tags {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Tags", err)
			}
		}
	}
	if this.User != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.User); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("User", err)
		}
	}
	for _, item := range this.Comments {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Comments", err)
			}
		}
	}
	for _, item := range this.Users {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Users", err)
			}
		}
	}
	if this.Ext != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Ext); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Ext", err)
		}
	}
	return nil
}
