// Code generated by protoc-gen-enum. DO NOT EDIT.
// source: common/common.enum.proto

package common

import (
	"errors"
	"github.com/liov/tiga/utils/strings"
	"io"
)

func (x RedisIndex) String() string {
	switch x {
	case RedisIndexPlaceholder:
		return "占位"
	case RedisIndexFlag:
		return "标志"
	case RedisIndexSys:
		return "系统"
	case RedisIndexCron:
		return "定时任务"
	}
	return ""
}

func (x RedisIndex) MarshalGQL(w io.Writer) {
	w.Write(stringsi.QuoteToBytes(x.String()))
}

func (x *RedisIndex) UnmarshalGQL(v interface{}) error {
	if i, ok := v.(uint32); ok {
		*x = RedisIndex(i)
		return nil
	}
	return errors.New("枚举值需要数字类型")
}

func (x ObjectType) String() string {
	switch x {
	case ObjectPlaceholder:
		return "占位"
	case ObjectContent:
		return "内容"
	}
	return ""
}

func (x ObjectType) MarshalGQL(w io.Writer) {
	w.Write(stringsi.QuoteToBytes(x.String()))
}

func (x *ObjectType) UnmarshalGQL(v interface{}) error {
	if i, ok := v.(uint32); ok {
		*x = ObjectType(i)
		return nil
	}
	return errors.New("枚举值需要数字类型")
}
